name: ubuntu cross-pi

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        bash tools/build.sh

    - uses: actions/upload-artifact@v2
      with:
        name: raspi-toolchain
        path: raspi-toolchain.tar.gz

    - uses: actions/upload-artifact@v2
      with:
        name: raspi-toolchain-install
        path: raspi-toolchain-install.tar.gz        